/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as taskManagerSol from "./TaskManager.sol";
export type { taskManagerSol };
export type { TaskEscrow } from "./TaskEscrow";
export type { TaskToken } from "./TaskToken";
