/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITaskEscrow,
  ITaskEscrowInterface,
} from "../../../contracts/TaskManager.sol/ITaskEscrow";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "taskId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "release",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITaskEscrow__factory {
  static readonly abi = _abi;
  static createInterface(): ITaskEscrowInterface {
    return new Interface(_abi) as ITaskEscrowInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITaskEscrow {
    return new Contract(address, _abi, runner) as unknown as ITaskEscrow;
  }
}
